version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/dev
    # This is where ports would go
    networks:
      - dev-network
  # Additional services here
# volumes here
networks:
  dev-network:
    driver: bridge  
